name: food_amateur
description: Save your best food memories.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: 3.3.9

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_google_places: ^0.3.0
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  go_router: ^5.2.4
  hooked_bloc: ^1.3.0
  injectable: ^2.1.0
  logger: ^1.1.0
  theme_tailor_annotation: ^1.0.3




dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  theme_tailor: ^1.0.8
  


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/illustrations/
    - assets/icons/

  
  fonts: 
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf #900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf #900
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf #700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf #700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf #800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf #800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf #200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf #200
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf #400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf #300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf #300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf #500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf #500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf #400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf #600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf #600
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf #100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf #100

